### ISSUE TITLE
[PROJECT] Issues, Bounties, People etc.

### ISSUE THREAD

**Issue by abebeos** [ArtemGr/gun#10]
"I'd welcome guidance in that." - says the readme.

Give me few days, until then, avoid filing many new issues (e.g. prefer one major-issue with multiple entries, which can later become issues/bounties) like

[MAJOR] Stabilize towards V1.0.0

- [ ] Do this and that
- [ ] Rephrase this and tha
- [ ] Document xyz

EDIT: some systems name such issues EPIC, personally I use either [MAJOR] or just [TASK].

**Comment by ArtemGr** [comment]
So what you're saying is that we need a plan?
In order to help people see where we're going with this and the riches that await there?

**Comment by abebeos** [comment]
> So what you're saying is that we need a plan?

just a break, to await the upcoming 2nd opinion (mine).

and yes, work-plans, to avoid filing too much issues before they mature.

> In order to help people see where we're going with this and the riches that await there?

this is in the back of my head, reaching this point in estimated 2 weeks (well, if you can manage my frankness so long...)

**Comment by ArtemGr** [comment]
> well, if you can manage my frankness so long...

Frankness is good, but there is also a matter of your emotional state (which became apparent to me in the README conversation that we have removed now). I find using the RAGE affective network (as identified by Panksepp) to be useful for working along, but it's a poor choice for collaboration. I can only work with you if you show a capacity and willingness to communicate predominately from the so-called "positive" emotional states.

**Comment by abebeos** [comment]
> "positive" emotional states.

I am in a positive emotional state.

As for "Panksepp", "Eminen" and the rest: I don't care in the given context. You should talk once for yourself, with your own logic. And you should give your brain much much time to digest the lifes work of others. Quite limited capacity, we're essentially monkeys.

Now, my understanding is that your plea for help ("I'd welcome guidance in that.") is bound to your quite ordinary and disgustingly boring "communication fascism", which I of course reject.

So, closing this, before your force another 17 quotes upon me....

Poor me want to keep positive emotional state!

**Comment by ArtemGr** [comment]
https://youtu.be/mpSI7p43Dmw
