### ISSUE TITLE
port the `get` function

### ISSUE THREAD

**Issue by ArtemGr** [ArtemGr/gun#11]
Looks like we're missing the basic user-facing functions, `get` and `put`   D
I'm tracing the `get` function in JS and it would help a lot to see the respective parts in a Rust interlinear!

**Comment by abebeos** [comment]
> I'm tracing the `get` function in JS

What do you mean with "I'm tracing" ?

**Comment by GiraffeKey** [comment]
Taking

**Comment by ArtemGr** [comment]
Hey! Thanks for the https://github.com/ArtemGr/gun/commit/9431ef7c4097695066eaac7772bfdf2305492834, I guess I would now have something to compare the JS tracing with   <3

**Comment by GiraffeKey** [comment]
Yeah the final implementation of get should be done by the end of today and is gonna look pretty different

**Comment by GiraffeKey** [comment]
Well it's a very basic implementation but it works!

"get.once" and "get.on" are now functional and "get.put" has a temporary hack for testing purposes but the hardcoded data functions on a real network.

I decided to switch back to tokio as plain tungstenite was giving me problems and I also felt async is much more user-friendly. Should be okay as long as futures can work in wasm and kernels.

**Comment by GiraffeKey** [comment]
So, should I get put fully working and then close the issue?

**Comment by GiraffeKey** [comment]
It's actually been said that the user API has been the hardest thing to implement and there is a lot that goes behind many of the functions that look simple such as chain, put, etc. So I'm not really sure how "finished" should be defined with this one because working on the API is like cutting off hydra heads.

**Comment by ArtemGr** [comment]
Hey, @GiraffeKey !
Did a video reply!

https://youtu.be/QnbcxdLRsdg

> It's actually been said that the user API has been the hardest thing to implement

Been there, done that  D

Some API designs are inheently harder to implement and/or understand/maintain

> and there is a lot that goes behind many of the functions that look simple such as chain, put, etc. So I'm not really sure how "finished" should be defined with this one because working on the API is like cutting off hydra heads.

No need to refactor and optimize here, but I'll need to catch up with you before I can close the issue.
You can go ahead and close the issue yourself though, if it feels right?

**Comment by amark** [comment]
@ArtemGr @GiraffeKey correct, and beware, its only the wire/protocol code that is mostly solid & worth porting (altho new performance version does have some changes coming up), the JS chaining API code is pretty ugly and probably more of a headache than not. I think rust should have a simpler API, no?

**Comment by GiraffeKey** [comment]
Hey, nice video, it was very explanatory.

Yeah I simply wasn't paying much attention to the positions of others and trying to rush through things too much (I tend to be a bit impatient and I also have very asocial tendencies).

There were many core GUN concepts that I still do not understand on a very fundamental level and certain parts of the code focused more on the porting/logic/getting things done than planning/good practices/design.

So I'll slow it down and start paying more attention to the collective, perhaps write some much needed tests, add some comments/documentation to the codebase, set up a benchmarking suite with Criterion, etc.

**Comment by ArtemGr** [comment]
> Yeah I simply was ... trying to rush through things too much

And it's awesome that you did!
Great to have the working Rust interlinear!

Now, the benefit of the cross-functional teams is to have both the people who can breach in guns blasing, and then people who can later move slow and do a CSI on the scene   D

> So I'll slow it down and start paying more attention to the collective

Yeah, it pays to pay attention.
And you're more than welcome to move fast and make the port useful to you!
It's just I'll need some time to catch up. Busy with MUSL builds and patching websocket implementations right now.

**Comment by GiraffeKey** [comment]
I'm going to close this as the mentioned task has been completed. We can open other issues for other parts of the API.
