### ISSUE TITLE
Make a Gun Observable

### ISSUE THREAD

**Issue by ArtemGr** [ArtemGr/gun#4]
Evaluate withether the [Observable](https://observablehq.com/demo) is indeed as convenient for visualization as it seems to be.
By doing something practical, like making a Gun demo.
If the Observable proves to be useful, we might then render some of the [trace](1) with it.

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=94916868)](https://www.bountysource.com/issues/94916868-make-a-gun-observable)

**Comment by i001962** [comment]
I'm not sure how far you want to take this. Is it that you want to see d3 hooked up to a notebook that pulls in gun data? (I'm in the discord if you want to chat there.)

I ran into some issues (due to my lack of experience) requiring gun as a module. This is what I have so far....

https://observablehq.com/@i001962/gundb

**Comment by ArtemGr** [comment]
Awesome, @i001962 !

I did a fork, https://observablehq.com/@artemgr/gundb,
and I've also loaded a video with a bunch of optional questions,
here: https://youtu.be/QgyOiCjOics

I'll wait and see if you (or someone) would like to improve the Observable tutorial further, and then we'll close the issue, knowing that we can proceed with Observable as a wiki-with-graphics for [tracing](1)! Thanks!

**Comment by i001962** [comment]
Sadly the .on step isn’t reacting to the change automatically when I test it. I’ve needed to execute the observable step by hand to see the change in name from the prior step. (At least from mobile.). I like what you’ve done to start documenting what’s happening. The require step is kinda hacky. I wonder if there’s something on the gun side that would make the module require easier. https://observablehq.com/@observablehq/introduction-to-require

 It’s unlikely that I’ll pick this up from here as you know... time.

**Comment by ArtemGr** [comment]
Thanks again for getting this going, @i001962 !
If you want to take the bouty
( even if only for the sake of a new experience  = D
then please apply on BountySource  D

**Comment by i001962** [comment]
Keep it or better yet add it to another request to enlarge its bounty.

**Comment by ArtemGr** [comment]
Improved by Fil: https://observablehq.com/d/d90c2f589bba9aed

**Comment by ArtemGr** [comment]
A new version from @i001962 using [viewof](https://observablehq.com/@tmcw/exploring-viewof): https://observablehq.com/@i001962/gundb

**Comment by ArtemGr** [comment]
Just in case, a snipper for loading CommonJS modules: https://github.com/ArtemGr/bounty/issues/28#issuecomment-808720230
