### ISSUE TITLE
Clarify README

### ISSUE THREAD

**Issue by abebeos** [ArtemGr/gun#9]
The current readme is a bit confusing, it is not clear what this project is about, additionally its written in 1st person.

Should be rewritten, ideally by a newcomer.

(saw this project on bountysource, came here to see what this is about)

**Comment by GiraffeKey** [comment]
Right well there is a link to what it is in the README that links to here: https://github.com/amark/gun

You can learn more about Gun here: https://gun.eco/docs/

And the initial development is following this: https://github.com/gundb/port

I will add a couple of these to the README to make it more obvious. If anyone wants to summarize the content present on these links to make this project independently explainable please do and send a PR.

**Comment by ArtemGr** [comment]
Nice to see you, @abebeos !
I agree, the README was created before we have the contributors, such as @GiraffeKey and @i001962. 
Now that we have considerable progress we'll need to expand it.
Thanks for taking the time to create the tracker entry. Will keep you posted  D

**Comment by abebeos** [comment]
Well, just be aware that after the update it's even worse now.

**Comment by ArtemGr** [comment]
@abebeos , you've made my day!

Still, for curiosity' sake, I've looked at the README of GCC, the project you're working on.
https://github.com/gcc-mirror/gcc/blob/master/README
What do you think about it?

**Comment by abebeos** [comment]
The project I'm working on is this https://github.com/abebeos/avr-gnu, with a quite limited audience.

GNU/GCC/FSF is a usability disaster, docs/resources/processes are a pure freak-show. Never take it as a reference for your work!

**Comment by abebeos** [comment]
> @abebeos , you've made my day!
> 
> I need not go any further, simply basking in the light of your frankness.

...grin...

**Comment by abebeos** [comment]
@ArtemGr , do I understand correct:

a) Your project is "gun for rust" or "rust for gun" (kind of a wrapper), and thus the project (repo) name should be either `gun-rust` or `rust-gun` or so? And not `gun` as you have now?

b) Is it possible that the gun folks means "distributed" and not "decentralized" ?

c) Place a bounty, I'll fix your readme (need a tiny non-code task to relax)

**Comment by ArtemGr** [comment]
a) The database is just GUN. As of now it is most known for the original JS version, so that's what we referring to, but in the future the Rust port will hopefully stand just as tall.

b) Decentralized most likely harks to https://en.wikipedia.org/wiki/Decentralized_finance and https://en.wikipedia.org/wiki/Decentralized_application, the GUN is seen as aiming at facilitating such technologies.

c) Here you go: https://www.bountysource.com/issues/94971657-clarify-readme !

> (EDIT: c means that all this looks interesting to me)

Swell!
And figured as much, you wouldn't waste your time here otherwise  D
Glad to have another pair of eyes!

**Comment by GiraffeKey** [comment]
Gun is peer-to-peer

**Comment by abebeos** [comment]
a) so you are doing a complete port, assuming binary & api compatible. Why? For better speed? Just to make rust-devs happy?

b) I see. The crypto hick-hack "decentralization" is a bit misleading, it somehow implies that Gun(p2p-db) has a blockchain layer (though "decentralization" is not exclusive to blockchain).

c) curious: Why $83 and not $80 or $85 ?

**Comment by ArtemGr** [comment]
a) Personally I had good experience with offline-first databases in Rust, with using CRDTs, and over time I shifted from the idea of using a "one-size-fits-all" blockchain consensus to an idea of a lightweight and pluggable JIT-consensus. Automatic zero-maintenance peer discovery has also long been on my wishlist. Making the database modular should help with improving it further, trying new stuff when needed. Being primarily a Rust dev I want to be happy.

b) GUN is not by any means finished. When I use the word "port" I mostly mean a version of the system in a particular language. The Rust version will evolve alongside the JS one. As far as I can see, the idea is indeed for GUN to integrate tightly with some of DeFi. Mark might clarify, but it's not a priority, we're not using a [Waterfall](https://en.wikipedia.org/wiki/Waterfall_model).

c) Stochastic process   D
I don't have a better example at hand than https://arxiv.org/pdf/0907.0455.pdf ?

**Comment by abebeos** [comment]
I am making questions in order to shrink information down to a concise word. Your answers cause an "explosion of complexity", which will "train" me to simply... not ask you anymore, or to ask you with checkboxes whenever possible. Be aware of this. If you have the tendency to describe, then:

- give first(!) the compact answer, and add any elaborations later.

a) Do you

- [ ] Port the GunDB/JS to Rust (no dependency to GunDB/JS)?
- [ ] Produce Rust Wrappers (which depend on GunDB/JS) ?

b) GunDB README needs to be reworked (it tops even GCC in messyness), but some single-line descriptions  gave me a quite good picture of it. So, all good for now.

c) My stochastic (as in στοχασμός) process forces me to filter redundant (for the achievement of the task at hand) information, so, I'll not read the pdf now. For now: try to avoid any distractions. Even placing a bounty of 83 instead of normalized 80 or 85 can trigger a (redundant) analysis in high analytic brains. 

(and now, between us, the full truth: I'm assessing you. I'll look at your full writings here to a later point.)

**Comment by abebeos** [comment]
> one-size-fits-all a-la-blockchain consensus to an idea of a lightweight and pluggable JIT-consensus.

In one sentence: what is a JIT-consensus?

**Comment by ArtemGr** [comment]
c) That's ASMR for you. Per orienting reflex, people are pleasantly attracted to a moderately novel stimulus. A sound that is familiar yet new and unique is much more interesting. But when you're using the RAGE affective network to fuel your work and keep you from distractions then your outlook on that is a tad different.

> (and now, between us, the full truth: I'm assessing you. I'll look at your full writings here to a later point.)

I know what you mean. First time I saw this pattern described was in Laurell K. Hamilton novel, where the character reflected on how she pokes at relationships   D

**Comment by abebeos** [comment]
> c) That's ASMR for you.
[...]

filtering now brutally = mental bypass
 
> > (and now, between us, the full truth: I'm assessing you. I'll look at your full writings here to a later point.)
> 
> I know what you mean. First time I saw this pattern described was in Laurell K. Hamilton novel, where the character reflected on how she pokes at relationships D

So many books.  I'm illiterate, 0 books in my library.

**Comment by abebeos** [comment]
(please do not add new content to answers)

**Comment by abebeos** [comment]
(please do not shred original quotes. I wrote "In one sentence: what is a JIT-consensus?")
> > what is a JIT-consensus?
> 
> So Alice and Bob
[...]

Not one sentence, ignoring (not reading).

**Comment by ArtemGr** [comment]
Nah, I edit my posts sometimes because I don't care to notify you about updates. If you'll get back to them then it might worth your time to see the improved version, if you're not going back to them then why bother asking you to?

**Comment by abebeos** [comment]
You write, someone replies to the specific writing, you change the writing, the answer relates now to a different writing. This is bad. Avoid changing you writings.

**Comment by abebeos** [comment]
> You don't have to notify me on that, most of what I post is entirely optional and skippable D

You are not the center of this here.

**Comment by ArtemGr** [comment]
Nah, change is good, certainty is an illusion.

**Comment by abebeos** [comment]
> Nah, change is good, 

yes, that's why i usually shred my writings when done.

> certainty is an illusion.

certainty is what make it possible for you to type this message, thus it becomes visible to me somewhere else in the world. IT is based on certainty. Never ignore this when you kick around "freely", just because youcan. Within code, you can't.

**Comment by abebeos** [comment]
> > You are not the center of this here.
> 
> My point exactly.

the result is.

* A revised README
* A working gundb-rust
* ...

**Comment by ArtemGr** [comment]
> Within code, you can't

You kind of can, that's exploratory programming for you

**Comment by abebeos** [comment]
> > Within code, you can't
> 
> You kind of can, that's exploratory programming for you
> 
> Certainty is something we eventually converge on, and it's never a binary 100% one

Well, now you're getting funny, and a bit insulting (to your own intelligence).

Enough for me, I'll take a look later at the README.

Be certain!

**Comment by ArtemGr** [comment]
It is certainly useful to "buy into" something, like when you buy in into the certainty of your code.
But it is also useful to be able to step out of your certainty "trance" and look at things in persepective.
Particularly when different people interact, each coming into a conversation with their own set of certainties/platitudes

**Comment by abebeos** [comment]
trance, delirium, mushrooms... shredded everything... so freeing. In essence, even the essence is not essence.

cu!

**Comment by abebeos** [comment]
> Repository owner deleted a comment from abebeos 40 minutes ago 

A bit brutal...

Repeating the comment 
(will deleted at some point myself...):

trance, delirium, mushrooms... shredded everything... so freeing. In essence, even the essence is not essence.

cu!

**Comment by ArtemGr** [comment]
Going to move the bounty to #11
